### ISSUE TITLE
Too many arguments for function call by nimbus 1.2.0 in cocoapods

### ISSUE THREAD

**Issue by aelam** [jverkoey/nimbus#596]
I added nimbus 1.2.0 to my new project from cocoapods. It can be compiled success.
It's in the file "NIButtonUtilities.h"
Then I change to `pod 'Nimbus',:head` , the first problem is gone but another issue appeared
One nimbus block is incompatible with AFNetworking block 
![2015-03-10 1 19 16](https://cloud.githubusercontent.com/assets/232337/6569610/58e4bafa-c728-11e4-87a8-bf612d340ac4.png)

![2015-03-10 1 22 01](https://cloud.githubusercontent.com/assets/232337/6569622/91c8ab74-c728-11e4-8deb-aa19a4a8abfa.png)

`

**Comment by aelam** [comment]
I think the first issue is fixed. 
But the second issue seems have a long time.

**Comment by javenl** [comment]
I have the same problem, how to fixed this bug?

**Comment by aelam** [comment]
pod nimbus, :head

**Comment by javenl** [comment]
Thanks and I try it. But the second issue is still appeared. I have to replace 'NSInteger' to 'long long' in the pod file to fixed bug. Whenever I 'pod update' again, I need to fixed again. How you any idea for me?

**Comment by aelam** [comment]
Just use what you need 
Such as  

    Pod nimbus/Core
    Pod nimbus/Model


发自我的 iPhone

**Comment by wonderffee** [comment]
For the first issue, it can be solved by using use :head.
For the second issue, use submodule you need, such as "Pod nimbus/Core" and so on, not "Pod nimbus"
And the same, use :head, otherwise the first issue appears again.
example:
pod 'Nimbus/Core', :head
pod 'Nimbus/Launcher', :head
pod 'Nimbus/AttributedLabel', :head
